name: ok
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  image: ^4.2.0
  bot_toast: ^4.1.3
  permission_handler: ^11.3.1
  pull_to_refresh: ^2.0.0
  flutter_screenutil: ^5.9.3
  get: ^4.6.6
  cached_network_image: ^3.3.1
  flutter_smart_dialog: ^4.9.7+7
  visibility_detector: ^0.4.0+2
  dio: ^5.4.3+1
  get_it: ^7.7.0
  shared_preferences: ^2.2.3
  auto_route: 8.1.3
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: null # flutter packages pub run build_runner build
  build_runner: null
  flutter_lints: ^3.0.0
  auto_route_generator: 8.0.0

# 图片资源本地化命令行 flutter packages pub run build_runner build
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  lineLength: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  assets:
    enabled: true
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
